server:
  port: 9000
  

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    register-with-eureka: true  #註冊到Eureka註冊中心
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"